
export const JOB_CODES = [
    { code: 'ZE', details: 'SEZ COKER- ELECTRICAL / LIGHT FIXING' },
    { code: 'ZCU', details: 'SEZ PLANT - CUI JOB' },
    { code: 'ZPB', details: 'SEZ FCC-PP BAR INSTALATION' },
    { code: 'ZI', details: 'SEZ REFINERY AREA - INSULATION REPAIR JOB' },
    { code: 'ZS', details: 'SEZ PLANT AREA - SHEET REPAIR & MAINTENNACE JOB' },
    { code: 'ZB', details: 'SEZ PLANT AREA - BULL PLUG INSPECTION' },
    { code: 'Z', details: 'SEZ - UT INSPECTION JON' },
    { code: 'ZC', details: 'SEZ - CABLE LAYING JOB' },
    { code: 'ZP', details: 'SEZ - PAINTING JOB' },
    { code: 'DP', details: 'DTA PAINTING JOB' },
    { code: 'DC', details: 'DTA COKER - CUI & MECHANICAL ACTIVITIES' },
    { code: 'DCR', details: 'DTA CRUDE - CABLE LAYING JOB' },
    { code: 'DD', details: 'DTA DHT / DTA INSPECTION JOB' },
    { code: 'DA', details: 'DTA AROMATIC - CABLE LAYING & ELECTRICAL ACTIVITIES' },
    { code: 'ZRS', details: 'SEZ RTF- SPRINKLER DE CHOKING' },
    { code: 'CRY', details: 'CRYOGENIC AREA - MTF ROOF SHEET STRENGTHENING JOB' },
    { code: 'DR', details: 'DTA RTF- SPARE TANK SPRINKLER REPLACEMENT JOB' },
    { code: 'SWB', details: 'SWRO- BUS BAR REMOVAL & INSTALLATION JOB' },
    { code: 'MCT', details: 'MTF-CRYOGENIC- PIPELINE BUFFING & THICKNESS SURVEY JOB' },
    { code: 'MTI', details: 'MTF - STOIRAGE TANK TRUSS INSPECTION' },
    { code: 'MTL', details: 'MTF - LEVEL SWITCH REMOVAL & REFIXING JOB' },
    { code: 'MTP', details: 'MTF PLANT - TANK WIND GIRDER MANUAL CLEANING AND PAINTING' },
    { code: 'PVS', details: 'PV SOLAR - TARPAULIN FIXXING JOB' },
    { code: 'RGR', details: 'RAIL GANTRY - ROOF TOP SHEET STRENGTHENING JOB' },
    { code: 'DRR', details: 'RRTF-STORAGE TANK INTERNAL TRUSS INSPECTION JOB' },
    { code: 'RRT', details: 'RRTF - ROOF TOP SHEET STRENGTHENING JOB' },
    { code: 'SWR', details: 'SWRO PLANT- ARV MAINTENANCE' },
    { code: 'SWP', details: 'SWRO- Structure Beam Manual Cleaning and Painting & loose sheet removing Job.' },
    { code: 'SWS', details: 'STORAGE TANK WIND GIRDER MANUAL CLEANING & VISUAL INSPECTION JOB' },
    { code: 'MTJ', details: 'MTF-JETTY AREA JOBS' },
    { code: 'MTM', details: 'MTF PLANT - MECHANICAL ACTIVITIES' },
    { code: 'MTB', details: 'MTF PLANT - ANTI BIRD NET RELATED JOB' },
    { code: 'MTT', details: 'MTF PLANT - THICKNESS SURVEY JOB' },
    { code: 'MTF', details: 'MTF PLANT - FOAM POURER CHAMBER RELATED JOBS' },
    { code: 'MTS', details: 'MTF PLANT - SPRINKLER SPOOL REPLACEMENT' },
    { code: 'MTC', details: 'MTF-CRYOGENIC- Corroded Scaffolding Removal Job.' },
    { code: 'X', details: 'MISS PUNCH - NO PUNCHING / LATE PUNCHING' },
    { code: 'KD', details: 'KITCHEN DUTY' },
    { code: 'Q', details: 'QUARANTINE' },
    { code: 'ST', details: 'STANDBY ON JOB / ACTIVE STANDBY' },
    { code: 'NWS', details: 'NON WORKING STANDBY' },
    { code: 'R', details: 'REPORTING / MATERIAL SHIFTING IN STORE' },
    { code: 'OS', details: 'OFF AGANIST WORKING ON SUNDAY' },
    { code: 'ML', details: 'MEDICAL LEAVE' },
    { code: 'L', details: 'LEAVE' },
    { code: 'TR', details: 'TRAINING' },
    { code: 'PD', details: 'PASS DAMAGE - RELIANCE LOST PASS REISSUE / DAMAGE PASS REISSUE' },
    { code: 'EP', details: 'ENTRY PASS GENERATION / ANNUAL RENEWAL / NEW PASS GNERATION FOR EXISTING PERSON' },
    { code: 'OFF', details: 'SUNDAY DUTY OFF' },
    { code: 'PH', details: 'PUBLIC HOLIDAY' },
    { code: 'S', details: 'STANDBY' },
    { code: 'CQ', details: 'COVID QUARANTINE' },
    { code: 'RST', details: 'RIL SAFETY TRAINING' },
];

export const JOB_CODE_COLORS: { [key: string]: { bg: string, text?: string, excelFill?: any } } = {
    'X':   { bg: 'bg-white', text: 'text-red-500', excelFill: { font: { color: { rgb: "FFFF0000" }}} },
    'ML':  { bg: 'bg-job-code-yellow', text: 'text-black', excelFill: { fgColor: { rgb: 'FFFFFF00' } } },
    'ST':  { bg: 'bg-job-code-fluorescent-blue', text: 'text-black', excelFill: { fgColor: { rgb: 'FF00BFFF' } } },
    'NWS': { bg: 'bg-job-code-violet', text: 'text-black', excelFill: { fgColor: { rgb: 'FF8A2BE2' } } },
    'Q':   { bg: 'bg-job-code-bright-blue', text: 'text-black', excelFill: { fgColor: { rgb: 'FF0000FF' } } },
    'OS':  { bg: 'bg-job-code-dark-orange', text: 'text-black', excelFill: { fgColor: { rgb: 'FFFF8C00' } } },
    'KD':  { bg: 'bg-job-code-pink', text: 'text-black', excelFill: { fgColor: { rgb: 'FFDB7093' } } },
    'TR':  { bg: 'bg-job-code-pink', text: 'text-black', excelFill: { fgColor: { rgb: 'FFDB7093' } } },
    'EP':  { bg: 'bg-job-code-dark-blue', text: 'text-black', excelFill: { fgColor: { rgb: 'FFB0C4DE' } } },
    'PH':  { bg: 'bg-job-code-dark-green', text: 'text-black', excelFill: { fgColor: { rgb: 'FF90EE90' } } },
    'OFF': { bg: 'bg-job-code-dark-gray', text: 'text-black', excelFill: { fgColor: { rgb: 'FFA9A9A9' } } },
    'L':   { bg: 'bg-job-code-red-light', text: 'text-black', excelFill: { fgColor: { rgb: 'FFFF0000' } } },
    'PD':  { bg: 'bg-job-code-fluorescent-green', text: 'text-black', excelFill: { fgColor: { rgb: 'FF00FF00' } } },
    'S':   { bg: 'bg-job-code-blue', text: 'text-black', excelFill: { fgColor: { rgb: 'FFbde2ff' } } },
    'CQ':  { bg: 'bg-job-code-blue', text: 'text-black', excelFill: { fgColor: { rgb: 'FFbde2ff' } } },
    'RST': { bg: 'bg-job-code-pink', text: 'text-black', excelFill: { fgColor: { rgb: 'FFDB7093' } } },
    'R':   { bg: 'bg-yellow-400', text: 'text-black', excelFill: { fgColor: { rgb: 'FFFFFF00' } } },
};
