
export const JOB_CODES = [
    { code: 'ZE', details: 'SEZ COKER- ELECTRICAL / LIGHT FIXING' },
    { code: 'ZCU', details: 'SEZ PLANT - CUI JOB' },
    { code: 'ZPB', details: 'SEZ FCC-PP BAR INSTALATION' },
    { code: 'ZI', details: 'SEZ REFINERY AREA - INSULATION REPAIR JOB' },
    { code: 'ZS', details: 'SEZ PLANT AREA - SHEET REPAIR & MAINTENNACE JOB' },
    { code: 'ZB', details: 'SEZ PLANT AREA - BULL PLUG INSPECTION' },
    { code: 'Z', details: 'SEZ - UT INSPECTION JON' },
    { code: 'ZC', details: 'SEZ - CABLE LAYING JOB' },
    { code: 'ZP', details: 'SEZ - PAINTING JOB' },
    { code: 'DP', details: 'DTA PAINTING JOB' },
    { code: 'DC', details: 'DTA COKER - CUI & MECHANICAL ACTIVITIES' },
    { code: 'DCR', details: 'DTA CRUDE - CABLE LAYING JOB' },
    { code: 'DD', details: 'DTA DHT / DTA INSPECTION JOB' },
    { code: 'DA', details: 'DTA AROMATIC - CABLE LAYING & ELECTRICAL ACTIVITIES' },
    { code: 'ZRS', details: 'SEZ RTF- SPRINKLER DE CHOKING' },
    { code: 'CRY', details: 'CRYOGENIC AREA - MTF ROOF SHEET STRENGTHENING JOB' },
    { code: 'DR', details: 'DTA RTF- SPARE TANK SPRINKLER REPLACEMENT JOB' },
    { code: 'SWB', details: 'SWRO- BUS BAR REMOVAL & INSTALLATION JOB' },
    { code: 'MCT', details: 'MTF-CRYOGENIC- PIPELINE BUFFING & THICKNESS SURVEY JOB' },
    { code: 'MTI', details: 'MTF - STOIRAGE TANK TRUSS INSPECTION' },
    { code: 'MTL', details: 'MTF - LEVEL SWITCH REMOVAL & REFIXING JOB' },
    { code: 'MTP', details: 'MTF PLANT - TANK WIND GIRDER MANUAL CLEANING AND PAINTING' },
    { code: 'PVS', details: 'PV SOLAR - TARPAULIN FIXXING JOB' },
    { code: 'RGR', details: 'RAIL GANTRY - ROOF TOP SHEET STRENGTHENING JOB' },
    { code: 'DRR', details: 'RRTF-STORAGE TANK INTERNAL TRUSS INSPECTION JOB' },
    { code: 'RRT', details: 'RRTF - ROOF TOP SHEET STRENGTHENING JOB' },
    { code: 'SWR', details: 'SWRO PLANT- ARV MAINTENANCE' },
    { code: 'SWP', details: 'SWRO- Structure Beam Manual Cleaning and Painting & loose sheet removing Job.' },
    { code: 'SWS', details: 'STORAGE TANK WIND GIRDER MANUAL CLEANING & VISUAL INSPECTION JOB' },
    { code: 'MTJ', details: 'MTF-JETTY AREA JOBS' },
    { code: 'MTM', details: 'MTF PLANT - MECHANICAL ACTIVITIES' },
    { code: 'MTB', details: 'MTF PLANT - ANTI BIRD NET RELATED JOB' },
    { code: 'MTT', details: 'MTF PLANT - THICKNESS SURVEY JOB' },
    { code: 'MTF', details: 'MTF PLANT - FOAM POURER CHAMBER RELATED JOBS' },
    { code: 'MTS', details: 'MTF PLANT - SPRINKLER SPOOL REPLACEMENT' },
    { code: 'MTC', details: 'MTF-CRYOGENIC- Corroded Scaffolding Removal Job.' },
    { code: 'X', details: 'MISS PUNCH - NO PUNCHING / LATE PUNCHING' },
    { code: 'KD', details: 'KITCHEN DUTY' },
    { code: 'Q', details: 'QUARANTINE' },
    { code: 'ST', details: 'STANDBY ON JOB / ACTIVE STANDBY' },
    { code: 'NWS', details: 'NON WORKING STANDBY' },
    { code: 'R', details: 'REPORTING / MATERIAL SHIFTING IN STORE' },
    { code: 'OS', details: 'OFF AGANIST WORKING ON SUNDAY' },
    { code: 'ML', details: 'MEDICAL LEAVE' },
    { code: 'L', details: 'LEAVE' },
    { code: 'TR', details: 'TRAINING' },
    { code: 'PD', details: 'PASS DAMAGE - RELIANCE LOST PASS REISSUE / DAMAGE PASS REISSUE' },
    { code: 'EP', details: 'ENTRY PASS GENERATION / ANNUAL RENEWAL / NEW PASS GNERATION FOR EXISTING PERSON' },
    { code: 'OFF', details: 'SUNDAY DUTY OFF' },
    { code: 'PH', details: 'PUBLIC HOLIDAY' },
    { code: 'S', details: 'STANDBY' },
    { code: 'CQ', details: 'COVID QUARANTINE' },
    { code: 'RST', details: 'RIL SAFETY TRAINING' },
];

export const JOB_CODE_COLORS: { [key: string]: string } = {
    'X': 'bg-job-code-red-light',
    'ML': 'bg-job-code-red-light',
    'ST': 'bg-job-code-blue',
    'NWS': 'bg-job-code-purple',
    'Q': 'bg-job-code-blue',
    'OS': 'bg-job-code-yellow',
    'KD': 'bg-job-code-blue',
    'TR': 'bg-job-code-pink',
    'EP': 'bg-job-code-green-light',
    'PH': 'bg-job-code-green-light',
    'OFF': 'bg-job-code-gray',
    'L': 'bg-job-code-red-light',
    'PD': 'bg-job-code-green-light',
    'S': 'bg-job-code-blue',
    'CQ': 'bg-job-code-blue',
    'RST': 'bg-job-code-pink',
    'R': 'bg-yellow-400 dark:bg-yellow-700', // Kept for 'R' as it's not in the image but in the list.
};
