import type { RequestListItem } from './types';

export const MOCK_REQUESTS: RequestListItem[] = [
  {
    id: '1',
    requestNo: '2026022858',
    status: 'LPO Generative Complete',
    requestOn: '2026-04-06',
    deliveryDate: '2026-04-10',
    addedBy: 'Harikrishnan Prakash Sailaja',
    doneBy: 'Sivaprasad Vijayan Sujatha',
    toBeDoneBy: 'Vijay Sai Sadanandan',
    requestedBy: 'Harikrishnan Prakash Sailaja',
    requirement: 'GSB 600 13MM DRILL MACHINE & GSR 120LI CORDLESS DRILL MACHINE APPROVAL REQUEST...',
    jobNo: 'IRA1336',
    category: 'Consumables',
    subDivision: 'RA',
  },
  {
    id: '2',
    requestNo: '2026C22654',
    status: 'Invoice From Supplier On Process',
    requestOn: '2026-03-30',
    deliveryDate: '2026-03-31',
    addedBy: 'Harikrishnan Prakash Sailaja',
    doneBy: 'Anandhu Anil Kumar',
    toBeDoneBy: 'Vijay Sai Sadanandan',
    requestedBy: 'Harikrishnan Prakash Sailaja',
    requirement: 'Third Party Inspection payment request - 0001554...',
    jobNo: 'IRA1130',
    category: 'Job Exp. - Subcontrator Payment',
    subDivision: 'RA',
  },
   {
    id: '3',
    requestNo: '2026C22190',
    status: 'Material Delivery Full Delivery',
    requestOn: '2026-03-10',
    deliveryDate: '2026-03-12',
    addedBy: 'Harikrishnan Prakash Sailaja',
    doneBy: 'Anandhu Anil Kumar',
    toBeDoneBy: 'Vijay Sai Sadanandan',
    requestedBy: 'Harikrishnan Prakash Sailaja',
    requirement: 'Third Party Inspection payment request - 0001398...',
    jobNo: 'IRA1434',
    category: 'Job Exp. - Subcontrator Payment',
    subDivision: 'RA',
  },
   {
    id: '4',
    requestNo: '2026B21947',
    status: 'Material Delivery Full Delivery',
    requestOn: '2026-02-28',
    deliveryDate: '2026-03-02',
    addedBy: 'Harikrishnan Prakash Sailaja',
    doneBy: 'Anandhu Anil Kumar',
    toBeDoneBy: 'Vijay Sai Sadanandan',
    requestedBy: 'Harikrishnan Prakash Sailaja',
    requirement: 'Third Party Inspection payment request - 0001385...',
    jobNo: 'IRA1130',
    category: 'Job Exp. - Subcontrator Payment',
    subDivision: 'RA',
  },
   {
    id: '5',
    requestNo: '2026B21906',
    status: 'Employee Advance',
    requestOn: '2026-02-27',
    deliveryDate: '2026-02-28',
    addedBy: 'Harikrishnan Prakash Sailaja',
    doneBy: 'Anandhu Anil Kumar',
    toBeDoneBy: 'Vijay Sai Sadanandan',
    requestedBy: 'Harikrishnan Prakash Sailaja',
    requirement: 'Request for Purchase of Tables - Jamnagar...',
    jobNo: 'IRA1422',
    category: 'Job Exp. - Others',
    subDivision: 'RA',
  },
  {
    id: '6',
    requestNo: '2026A20549',
    status: 'SAP Entry(SO,WO) Complete',
    requestOn: '2026-01-23',
    deliveryDate: '2026-01-27',
    addedBy: 'Harikrishnan Prakash Sailaja',
    doneBy: 'Anjali Aravind',
    toBeDoneBy: 'Shiju Babu',
    requestedBy: 'Harikrishnan Prakash Sailaja',
    requirement: 'Purchase of Print head, inner, rear, pinch, paper pickup arm guide unit & pcb sensor & service charg...',
    jobNo: '',
    category: 'IT',
    subDivision: 'RA',
  },
  {
    id: '7',
    requestNo: '2026A20279',
    status: 'Material Delivery Full Delivery',
    requestOn: '2026-01-15',
    deliveryDate: '2026-01-16',
    addedBy: 'Harikrishnan Prakash Sailaja',
    doneBy: 'Anandhu Anil Kumar',
    toBeDoneBy: 'Shiju Babu',
    requestedBy: 'Harikrishnan Prakash Sailaja',
    requirement: 'Third Party Inspection payment request- 0001079...',
    jobNo: 'IRA1295',
    category: 'Job Exp. Subcontrator Payment',
    subDivision: 'RA'
  }
];
